import React from "react"
import Layout from "../components/layout"

export default () => (
  <div>
    <Layout subHeader='Manifiesto'>
	    <article>
		    <p>Parece que en los últimos años un gran número de pequeñas e importantes resistencias están ocurriendo por todo el mundo, cada una con su valor de diversidad y articulación. A la vez, el resurgimiento de una nueva y potente derecha nos hace sonar la alarma sobre el futuro de nuestra sociedad y los daños que estos movimientos tóxicos pueden incurrir. El sistema capitalista puede llegar a dominar los espacios que compartimos, y con sutileza, acaba ahogando opiniones más diversas o perspicaces al perpetrar reglas rígidas en cómo debemos realizar nuestras prácticas. Las preguntas pertinentes son múltiples, tales como qué grado de intervención se necesita o qué responsabilidad es necesaria para garantizar que las prácticas autónomas y antiautoritarias se sostengan.</p>
		    <p>Mal de ojo, poéticamente aludido como esta fuerza metafísica y abstracta, es la condición mística que aludimos al hacernos capaces de desdoblar las aristas del Orbe a fin de que los reflejos de este mundo también sufran con lo que sentimos dentro. Ojo es quizás la palabra que nos ha sido legada intacta a través de la cual todavía es posible atisbar el principio de la vida en sí. El ojo cuando se acerca a la mirada, destruye, reconstruye o le da vida a las imágenes que se asoman. En nuestra cabeza somos capaces de recrear lo que vemos, y en un parpadeo incontrolable, lo que vemos nos ofrece un puñado de informaciones distorsionadas, escorzos de pared y calle que reanudan una obtusa espiritualidad bajo una luz ciega que viene del sol o en la ausencia de él.</p>
		    <p>La habilidad de interferir en el campo visual rutinario y de ver en lo invisible es más que extraordinario; reclamar a través de la imágen resquicios de humanidad - lo poco que nos queda - es tarea de valientes. Entender este mundo nunca ha sido ni será una labor a ser desprendida sin coraje, pues aquellos que se dedican a registrar los movimientos de nuestras vidas tiene un valor de arrojo vital que desafortunadamente se nos escapa reconocer.</p>
		    <p>Al recopilar el trabajo fotográfico registrado por fotógrafos en todo el mundo, el resultado puede ser inesperado y lo que queremos es encontrarnos con esta sorpresa. De ser capaces de identificar los movimientos que son registrados por detrás del campo visual rutinario y de materializarlo en forma de investigación social. </p>
		    <p>El resultado será una publicación acompañada de una exposición que refleja las diversas voces alrededor de este mundo y de conectarlas entre sí. Nuestra idea es de hacerlas ver, hacerlas removerse y de apuntar hacia el enemigo de manera objetiva y enunciativa. Denunciar el fascismo generalizado por medio de la fotografía y hacer ver los movimientos que luchan contra él.</p>
		    <h3>Objetivos</h3>
		    <p>A través de la fotografía, este proyecto conjuga la voluntad trascendente de hacer ver la intimidad de un ajetreo escondido de resistencias que existen en todo el mundo. Desde el movimiento okupa hasta a la lucha LGTBI, o de proyectos ensordecedores del punk o del trap, de resistencias potentes en contra de la gentrificación o lo que tradicionalmente se llama el movimiento antifascista, queremos registrar lo que cada uno de estos movimientos tienen en común y cómo las diferencias de articulación política entre una perspectiva europea y una perspectiva sudamericana (por nombrar dos perspectivas diferentes) pueden reflejar en la fotografía y cómo la misma puede ser utilizada como objeto político. En este contexto, la fotografía nos servirá para hacer memoria, registrar la labor política de grupos organizados disidentes y de reafirmar quiénes somos cuando parece que se nos acaba el aliento. </p>
		    <p>Este proyecto emerge con la urgencia de “autoabordarnos” con firmeza, de reivindicar la vida que nos arrebata el enemigo y de vernos a nosotros mismos reflejados en lo que llamamos de presente. La urgencia que atisba el ojo de los fotógrafos en todo el mundo es la afirmación impávida de que aún tenemos la voluntad de indagar cómo podemos actuar.</p>
		    <p>Lo que queremos extraer de este proyecto es de entender cómo los movimientos disidentes en contra del sistema capitalista están actuando para desdoblar las prácticas represivas que nos empujan a vivir. Aquí queremos hacerlas ver, darles prestigio y protagonismo y a través de un proceso investigativo, queremos clusterizar cada una de las resistencias identificadas y conectarlas entre sí para entender hacia dónde estamos yendo y cómo nos estamos movimentando ahora mismo. </p>
	    </article>
    </Layout>
  </div>
)